Metadata:
        AWS::CloudFormation::Interface:
                ParameterGroups:
                        - Label:
                                default: "EC2 Instance Configuration"
                          Parameters:
                                  - InstanceTypeEnvironment
                        - Label:
                                default: "Environment Configuration"
                          Parameters:
                                  - KeyPair
                ParameterLabels:
                        InstanceTypeEnvironment:
                                default: "Which Environment are we planning to deploy our task too"
                        KeyPair:
                                default: "Be Aware once Key Pair is chosen, you can't change it"
                                    
Parameters:
        KeyPair:
                Type: AWS::EC2::KeyPair::KeyName
                Description: Choose the KeyPair to connect to the instance
        InstanceTypeEnvironment:
                Type: String
                Default: dev
                AllowedValues:
                        - dev
                        - prod
                Description: Choose Your Environment
Mappings:
        MyRegionMap:
                us-east-1:
                        AmiId: ami-047a51fa27710816e
                us-west-2:
                        AmiId: ami-0e999cbd62129e3b1
        MyEnvironmentMap:
                dev:
                        instanceType: t2.micro
                prod:
                        instanceType: t2.small
Resources:
        MyVMInstance:
                Type: AWS::EC2::Instance
                Properties:
                        ImageId: !FindInMap
                        - MyRegionMap
                        - !Ref 'AWS::Region'
                        - AmiId
                        InstanceType: !FindInMap
                        - MyEnvironmentMap
                        - !Ref InstanceTypeEnvironment
                        - instanceType
                        KeyName: !Ref KeyPair

