Parameters:
        S3BucketName:
                Type: String
                Description: |
                        Name of S3 bucket, make sure it is the same as that of domain name
                        For example if the domain is- abc.tk the bucket name should be the same abc.tk


Resources:
        MyS3Bucket:
                Type: AWS::S3::Bucket
                Properties:
                        BucketName: !Ref S3BucketName
                        WebsiteConfiguration:
                                 ErrorDocument: error.html
                                 IndexDocument: index.html
                        AccessControl: PublicRead
        MyHostedZone:
                Type: AWS::Route53::HostedZone
                Properties:
                        Name: !Ref S3BucketName
        MyRecordName:
                Type: AWS::Route53::RecordSet
                Properties:
                        AliasTarget:
                                 DNSName: !GetAtt MyS3Bucket.DomainName
                                 HostedZoneId: !GetAtt MyHostedZone.Id
                        HostedZoneId: !GetAtt MyHostedZone.Id
                        Name: www
                        Type: A




                        
